### ISSUE TITLE
Features and todo

### ISSUE THREAD

**Issue by eliassjogreen** [denosaurs/crux.land#5]
- [ ] dark mode (#4)
 - [ ] deploy to [deploy](https://deno.com/deploy) button for script preview
 - [ ] view [docs](https://doc.deno.land/) button for script preview
 - [ ] report script api
 - [ ] cli
 - [ ] caching
 - [ ] badword detection
 - [ ] browse aliases?
 - [ ] in browser editor
 - [ ] [wasm2wat](https://webassembly.github.io/wabt/doc/wasm2wat.1.html) preview for wasm scripts
 - [ ] postcss + tailwind, blocked by [tailwindcss#2971](https://github.com/tailwindlabs/tailwindcss/discussions/2971#discussioncomment-540847)

**Comment by somebody1234** [comment]
the ability to list versions for an alias would be nice too
